version: '3.5'

volumes:
  pgdata:
    driver: local
  node_modules:
    driver: local

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nest-oauth-container
    env_file:
      - '.env'
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
